### PR TITLE
Fix TypeError in the browser console.

### LINKED ISSUE #950: BUG TypeError in filter.js
**Bug description**
There is a TypeError in the browser console. 
**Expected change**
The browser console doesn't show the error message. (Just need to add if statement for document.getElementById('filter-all'))

**Screenshots**
Screenshot from 2024-05-07 11-32-50

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
## Related issue
fixes #950

## Updates 
Added if statement to the `document.getElementById('filter-all')` in `filter.js` to avoid TypeError.

### CODE REVIEW

File: taipy_theme/assets/js/filter.js [hunk 1]
```diff
@@ -41,7 +41,9 @@ function handleAll(callback) {
   else {
     // If no other checkbox is checked, check the "all" checkbox
     const otherFiltersChecked = newFilters.length > 0;
+    if ( document.getElementById('filter-all') ){
```
Comment (FabienLelaquais) [inline taipy_theme/assets/js/filter.js:44]: Sure thing!

**Review by FabienLelaquais — APPROVED** [review]
Good catch

File: taipy_theme/assets/js/filter.js (hunk 1 above)
Comment (FredLL-Avaiga) [reply taipy_theme/assets/js/filter.js:44]: Find the element twice...

**Review by FredLL-Avaiga — APPROVED** [review]
